#----------------------------------------------------------------------------------------
# Terraform Remote state config
#----------------------------------------------------------------------------------------
remote_state {
  backend = "s3"

  config = {
    bucket         = local.tf_bucket
    key            = "${local.repo_name}/${local.env}/${local.aws_region}/terraform.tfstate"
    profile        = local.aws_profile
    region         = local.aws_region
    encrypt        = true
    use_lockfile   = true
    dynamodb_table = "${local.prefix}-tfstate-lock"
  }
}

locals {
  tf_bucket   = get_env("TF_VAR_tf_bucket")
  repo_name   = get_env("TF_VAR_repo_name")
  env         = get_env("TF_VAR_env")
  aws_profile = get_env("TF_VAR_aws_profile")
  aws_region  = get_env("TF_VAR_aws_region")
  prefix      = get_env("TF_VAR_prefix")

  tf_version = trimspace(file("${get_terragrunt_dir()}/../../../.terraform-version"))
}

#----------------------------------------------------------------------------------------
# Generate provider block
#----------------------------------------------------------------------------------------

# When using this terragrunt config, terragrunt will generate the file "provider.tf" with the aws provider block before
# calling to OpenTofu/Terraform. Note that this will overwrite the existing file if it was generated by terragrunt; otherwise, error.
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
locals {
  tags = {
    Environment = "${local.env}"
    createdBy   = "Terraform"
    Team        = "TechHolding"
    RepoName    = "${local.repo_name}"
  }
}

provider "aws" {
  region  = "${local.aws_region}"
  profile = "${local.aws_profile}"
  
  default_tags {
    tags = local.tags
  }
}

terraform {
  required_version = "= ${local.tf_version}"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.82.0"
    }

    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4"
    }
  }
}

EOF
}

generate "backend" {
  path      = "backend.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
terraform {
  backend "s3" {}
}
EOF
}

#----------------------------------------------------------------------------------------
# Retryable Errors
#----------------------------------------------------------------------------------------
retryable_errors = [
  "(?s).*Error installing provider.*tcp.*connection reset by peer.*",
  "(?s).*ssh_exchange_identification.*Connection closed by remote host.*",
  "(?s).*net/http: TLS handshake timeout",
  "Unauthorized"
]

#----------------------------------------------------------------------------------------
# Terraform config
#----------------------------------------------------------------------------------------
terraform {
  source = "../..//stack/"

  before_hook "before_hook" {
    commands = [
      "apply",
      "plan"
    ]
    execute = ["bash", "../environments/tfsecrets", "use"]
  }

  extra_arguments "secrets_tfvars" {
    commands = [
      "plan",
      "apply"
    ]
    arguments = [
      "-var-file=secrets.tfvars"
    ]
  }

  after_hook "after_hook" {
    commands = [
      "apply",
      "plan"
    ]
    execute      = ["bash", "../environments/tfsecrets", "remove"]
    run_on_error = true
  }
}
