#!/bin/bash
set -e
### secret vars
_ARG=$1
_AWS_PROFILE=$TF_VAR_aws_profile
_AWS_REGION=$TF_VAR_aws_region
SSM_PATH=$TF_VAR_ssm_prefix/repo/$TF_VAR_repo_name

set -e
case $_ARG in
  use)
    ## secret vars
    aws --profile $_AWS_PROFILE --region $_AWS_REGION \
      ssm get-parameters-by-path --path $SSM_PATH \
      --with-decryption  --query "Parameters[*].[Name,Value]" --output text | \
      sed "s~$SSM_PATH/~""~g" | \
      sed "s/[[:blank:]]/\ =\ \"/g" | \
      sed s/$/\"/ > secrets.tfvars
    ;;
  remove)
    rm secrets.tfvars
    ;;
esac
