---
- name: Prepare host
  hosts: all
  gather_facts: false
  tasks:
    # psycopg2 needed for Postgresql operations
    - name: Install python packages
      pip:
        name: psycopg2-binary
        extra_args: --user
        executable: pip3


- name: a play that runs entirely on the ansible host
  hosts: all
  become: true
  vars_files: 'vars/{{ env }}.yml'
  tasks:
  - name: create bastion users
    user:
      name: '{{ item }}'
      shell: /bin/bash
    with_items: '{{ users }}'

  - name: "Add authorized keys"
    authorized_key:
      user: '{{ item }}'
      key: "{{ lookup('file','pubkeys/' + item + '.pub') }}"
      state: present
    with_items: '{{ users }}'

  - name: Create sudo group
    group:
      name: '{{ sudo_group }}'
      state: present

  - name: Disable Password Authentication
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^PasswordAuthentication'
      line="PasswordAuthentication no"
      state=present
      backup=yes

  - name: Disable Root Login
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^PermitRootLogin'
      line="PermitRootLogin no"
      state=present
      backup=yes
    notify:
      - restart ssh

  - name: Sudo users
    user:
      name: "{{ item }}"
      groups: '{{ sudo_group }}'
      append: yes
    with_items: '{{ sudo_users if sudo_users is iterable else [] }}'

  - name: Add sudo group to the sudoers
    copy:
      dest: "/etc/sudoers.d/sudo_group"
      content: "%{{ sudo_group }}  ALL=(ALL)  NOPASSWD: ALL"

  - name: Remove user from system
    ansible.builtin.user:
      name: "{{ item }}"
      state: "absent"
      remove: true
    with_items: '{{ remove_users  if remove_users is iterable else [] }}'

  handlers:
  - name: restart ssh
    service:
      name=sshd
      state=restarted
